general.import = ["~/.config/myrice/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10

[window]
padding = { x = 14, y = 14 }
decorations = "None"
